name: ci

on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the short commit_id of your git push
        id: short_sha
        shell: bash
        run: | 
            echo "COMMIT_ID=${GITHUB_SHA::6}" >> ${GITHUB_ENV}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aumthakkar/3py-app:${{ env.COMMIT_ID }}
    
    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - name: Clone Github repo
        uses: actions/checkout@v6
    
      - name: Modify charts/values.yaml file
        shell: bash
        run: |
          echo "${{ needs.ci.outputs.commit_id }}"
          sudo apt update && sudo apt install python3-pip -y
          pip install yq --break-system-packages
          yq -Yi '.image.tag = "${{ needs.ci.outputs.commit_id }}"' charts/3py-app/values.yaml

      - name: Commit change back to your github repo
        uses: EndBug/add-and-commit@v9
        with:
          message: "updated Helm values.yaml with commit - ${{ needs.ci.outputs.commit_id }}"

      - name: Install ArgoCD App
        shell: bash
        run: |
          curl -ksSL -o /tmp/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /tmp/argocd
          sudo mv /tmp/argocd /usr/local/bin/argocd

      - name: ArgoCD Sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
          --grpc-web \
          --insecure \
          --username admin \
          --password ${{ secrets.ARGOCD_PASSWORD }}
          
          argocd app sync py-app-3